[package]
author = "poly000"
name = "ddlc_helper"
version = "1.1.1"
edition = "2018"
license = "MIT"
description = "DDLC word selecting helper."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
crossterm = "0.20.0"
